# Generated by Django 4.2 on 2023-04-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_login3"),
    ]

    operations = [
        migrations.CreateModel(
            name="signup2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("confirm_password", models.CharField(max_length=100)),
            ],
        ),
    ]
