# Generated by Django 4.2 on 2023-04-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_signup2"),
    ]

    operations = [
        migrations.CreateModel(
            name="payment2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Cardholder_name", models.CharField(max_length=100)),
                ("Card_number", models.BigIntegerField()),
                ("Expiry_date", models.CharField(max_length=10)),
                ("cvv", models.CharField(max_length=10)),
                ("save_card", models.BooleanField()),
            ],
        ),
    ]
