# Generated by Django 4.2 on 2023-04-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_payment2"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment2",
            old_name="Expiry_date",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="payment2",
            old_name="Cardholder_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="payment2",
            old_name="Card_number",
            new_name="number",
        ),
        migrations.RemoveField(
            model_name="payment2",
            name="save_card",
        ),
        migrations.AddField(
            model_name="payment2",
            name="checkbox",
            field=models.BooleanField(default=False),
        ),
    ]
