# Generated by Django 4.2 on 2023-04-18 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_payment2_checkbox"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment2",
            old_name="date",
            new_name="Expiry_date",
        ),
        migrations.RenameField(
            model_name="payment2",
            old_name="number",
            new_name="card_number",
        ),
        migrations.RenameField(
            model_name="payment2",
            old_name="name",
            new_name="cardholder_name",
        ),
    ]
