# Generated by Django 4.2 on 2023-04-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_rename_date_payment2_expiry_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment2",
            name="checkbox",
            field=models.BooleanField(default=False),
        ),
    ]
