# Generated by Django 4.2 on 2023-04-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_payment2_checkbox"),
    ]

    operations = [
        migrations.CreateModel(
            name="payment3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("Address", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("zip_code", models.BigIntegerField()),
                ("cardnumber", models.BigIntegerField()),
                ("Expiry_month", models.IntegerField()),
                ("cvv", models.CharField(max_length=10)),
            ],
        ),
    ]
